GET localhost:8080/getValueForPeriod
Content-Type: application/json

{
  "material_source_id": 1,
  "start": "2022-01-17",
  "finish": "2022-07-13"
}

###
GET localhost:8080/getNLastValues
Content-Type: application/json

{
  "material_source_id": 2,
  "property_id": 2,
  "n_values": 5
}

###
GET http://localhost:8080/getMaterialInfo
Content-Type: application/json

{
  "id": 2

}

###
GET localhost:8080/getMaterialList

###
GET localhost:8080/getPropertyList
Content-Type: application/json

{
  "material_source_id": "2"
}

###
POST localhost:8080/initImport


###
POST localhost:8080/addUniqueMaterial
Content-Type: application/json

{
  "name": "Test Material",
  "source": "Test Source",
  "market": "Test Market",
  "unit": "Test Unit"
}
###
POST localhost:8080/addValue
Content-Type: application/json

{
  "material_source_id": 1,
  "property_name": "med_price",
  "value_float": "100",
  "value_str": "",
  "created_on": "2015-10-15T14:00:13Z"
}

###
GET http://localhost:8080/getChart/2_2_11-13-2021_01-01-2022_0.png


