GET localhost:8080/getValueForPeriod
Content-Type: application/json

{
  "material_source_id": 1,
  "start": "2009-07-07",
  "finish": "2022-07-14"
}

###
GET localhost:8080/getNLastValues
Content-Type: application/json

{
  "material_source_id": 1,
  "n_values": 5
}


###
GET localhost:8080/getMaterials


###
POST localhost:8080/initImport


###
POST localhost:8080/addUniqueMaterial
Content-Type: application/json

{
  "name": "Test Material",
  "source": "Test Source",
  "market": "Test Market",
  "unit": "Test Unit"
}
###
POST localhost:8080/addValue
Content-Type: application/json

{
  "material_name": "Test Material",
  "source_name": "Test Source",
  "property_name": "med_price",
  "value_float": "100",
  "value_str": "",
  "created_on": "2015-10-15T14:00:13Z"
}

###
POST localhost:8080/addValue
Content-Type: application/json

{
  "material_name": "Test Material",
  "source_name": "Test Source",
  "property_name": "Test Property String",
  "value_float": "",
  "value_str": "string val",
  "created_on": "2015-02-15T14:00:13Z"
}
