# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import modify_docx_pb2 as modify__docx__pb2


class ModifyDocxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ModifyDocx = channel.unary_unary(
                '/modify_docx.ModifyDocx/ModifyDocx',
                request_serializer=modify__docx__pb2.ModifyDocxRequest.SerializeToString,
                response_deserializer=modify__docx__pb2.ModifiedDocxResponse.FromString,
                )
        self.TestFunc = channel.unary_unary(
                '/modify_docx.ModifyDocx/TestFunc',
                request_serializer=modify__docx__pb2.TestFuncRequest.SerializeToString,
                response_deserializer=modify__docx__pb2.TestFuncResponse.FromString,
                )


class ModifyDocxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ModifyDocx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestFunc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModifyDocxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ModifyDocx': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyDocx,
                    request_deserializer=modify__docx__pb2.ModifyDocxRequest.FromString,
                    response_serializer=modify__docx__pb2.ModifiedDocxResponse.SerializeToString,
            ),
            'TestFunc': grpc.unary_unary_rpc_method_handler(
                    servicer.TestFunc,
                    request_deserializer=modify__docx__pb2.TestFuncRequest.FromString,
                    response_serializer=modify__docx__pb2.TestFuncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'modify_docx.ModifyDocx', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModifyDocx(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ModifyDocx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/modify_docx.ModifyDocx/ModifyDocx',
            modify__docx__pb2.ModifyDocxRequest.SerializeToString,
            modify__docx__pb2.ModifiedDocxResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestFunc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/modify_docx.ModifyDocx/TestFunc',
            modify__docx__pb2.TestFuncRequest.SerializeToString,
            modify__docx__pb2.TestFuncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
