# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modify_docx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11modify_docx.proto\x12\x0bmodify_docx\"\"\n\x11ModifyDocxRequest\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\".\n\x14ModifiedDocxResponse\x12\x16\n\x0emodified_bytes\x18\x01 \x01(\x0c\"\x1f\n\x0fTestFuncRequest\x12\x0c\n\x04ping\x18\x01 \x01(\t\" \n\x10TestFuncResponse\x12\x0c\n\x04pong\x18\x01 \x01(\t2\xa6\x01\n\nModifyDocx\x12O\n\nModifyDocx\x12\x1e.modify_docx.ModifyDocxRequest\x1a!.modify_docx.ModifiedDocxResponse\x12G\n\x08TestFunc\x12\x1c.modify_docx.TestFuncRequest\x1a\x1d.modify_docx.TestFuncResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modify_docx_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MODIFYDOCXREQUEST']._serialized_start=34
  _globals['_MODIFYDOCXREQUEST']._serialized_end=68
  _globals['_MODIFIEDDOCXRESPONSE']._serialized_start=70
  _globals['_MODIFIEDDOCXRESPONSE']._serialized_end=116
  _globals['_TESTFUNCREQUEST']._serialized_start=118
  _globals['_TESTFUNCREQUEST']._serialized_end=149
  _globals['_TESTFUNCRESPONSE']._serialized_start=151
  _globals['_TESTFUNCRESPONSE']._serialized_end=183
  _globals['_MODIFYDOCX']._serialized_start=186
  _globals['_MODIFYDOCX']._serialized_end=352
# @@protoc_insertion_point(module_scope)
