package src

import "metallplace/internal/app/model"

var Materials = []model.Material{
	{"fe",
		"Iron ore (62% Fe)",
		"ferroalloynet.com",
		"Worldwide",
		"usd/t",
		"A",
		[]model.Property{{"price", "C", 3, "double"}},
	},

	{"fe",
		"Iron ore (65% Fe)",
		"ferroalloynet.com",
		"Worldwide",
		"usd/t",
		"A",
		[]model.Property{{"price", "H", 3, "double"}},
	},

	{"fe",
		"Iron ore (62% Fe)",
		"mysteel.net",
		"China",
		"usd/t",
		"A",
		[]model.Property{{"price", "M", 741, "double"}},
	},

	{"scrap",
		"Scrap 3A",
		"metalexpert.com",
		"Russia",
		"rub/t",
		"B",
		[]model.Property{{"min_price", "D", 3, "double"},
			{"max_price", "E", 3, "double"},
			{"med_price", "F", 3, "double"},
		},
	},

	{"scrap",
		"Scrap HMS (80:20)",
		"Not specified",
		"Turkey",
		"usd/t",
		"B",
		[]model.Property{{"min_price", "J", 209, "double"},
			{"max_price", "K", 209, "double"},
			{"med_price", "L", 3, "double"},
		},
	},
}
