package model

var InitMaterials = []Material{
	{"Iron Ore Raw",
		"Iron Ore Raw (62% Fe)",
		"ferroalloynet.com",
		"Global",
		"usd/t",
		"A",
		[]Property{{"med_price", "C", 3, "decimal"}},
	},

	{"Iron Ore Raw",
		"Iron Ore Raw(65% Fe)",
		"ferroalloynet.com",
		"Global",
		"usd/t",
		"A",
		[]Property{{"med_price", "H", 3, "decimal"}},
	},

	{"Iron Ore Raw",
		"Iron Ore Raw (62% Fe)",
		"mysteel.net",
		"China",
		"usd/t",
		"A",
		[]Property{{"med_price", "M", 741, "decimal"}},
	},

	{"Scrap",
		"Scrap 3A",
		"metalexpert.com",
		"Russia",
		"rub/t",
		"A",
		[]Property{{"min_price", "D", 3, "decimal"},
			{"max_price", "E", 3, "decimal"},
			{"med_price", "F", 3, "decimal"},
		},
	},

	{"Scrap",
		"Scrap HMS (80:20)",
		"Not specified",
		"Not specified",
		"usd/t",
		"A",
		[]Property{{"min_price", "J", 209, "decimal"},
			{"max_price", "K", 209, "decimal"},
			{"med_price", "L", 3, "decimal"},
		},
	},

	{"Coal",
		"Coal China",
		"mysteel.net",
		"Australia",
		"usd/t",
		"A",
		[]Property{
			{"med_price", "C", 3, "decimal"},
		},
	},

	{"Coal",
		"Coal China",
		"mysteel.net",
		"Russia",
		"usd/t",
		"A",
		[]Property{
			{"med_price", "H", 388, "decimal"},
		},
	},

	{"Metallurgical Coke",
		"Metallurgical Coke China",
		"steelmint.com",
		"Global",
		"usd/t",
		"B",
		[]Property{
			{"med_price", "D", 3, "decimal"},
		},
	},

	{"Metallurgical Coke",
		"Coking Coal Australia",
		"Not specified",
		"Not specified",
		"usd/t",
		"B",
		[]Property{
			{"med_price", "H", 3, "decimal"},
		},
	},

	{"Metallurgical Coke",
		"Coking Coal Russia",
		"Not specified",
		"Not specified",
		"usd/t",
		"B",
		[]Property{{"min_price", "L", 3, "decimal"},
			{"max_price", "M", 3, "decimal"},
			{"med_price", "N", 3, "decimal"},
		},
	},

	{"Cast Iron",
		"Cast Iron Black Sea",
		"steelmint.com",
		"Not specified",
		"usd/t",
		"B",
		[]Property{{"min_price", "D", 159, "decimal"},
			{"max_price", "E", 159, "decimal"},
			{"med_price", "F", 3, "decimal"},
		},
	},

	{"Cast Iron",
		"Cast Iron Russia",
		"Not specified",
		"Not specified",
		"rub/t",
		"B",
		[]Property{{"min_price", "J", 3, "decimal"},
			{"max_price", "K", 3, "decimal"},
			{"med_price", "L", 3, "decimal"},
		},
	},

	{"Steel",
		"Blank Black Sea",
		"steelmint.com",
		"Not specified",
		"usd/t",
		"A",
		[]Property{{"min_price", "D", 159, "decimal"},
			{"max_price", "E", 159, "decimal"},
			{"med_price", "F", 3, "decimal"},
		},
	},

	{"Steel",
		"Armature Black Sea",
		"Not specified",
		"Not specified",
		"usd/t",
		"A",
		[]Property{{"min_price", "J", 159, "decimal"},
			{"max_price", "K", 159, "decimal"},
			{"med_price", "L", 3, "decimal"},
		},
	},

	{"Steel",
		"Slab Black Sea",
		"Not specified",
		"Not specified",
		"usd/t",
		"A",
		[]Property{{"min_price", "P", 203, "decimal"},
			{"max_price", "Q", 203, "decimal"},
			{"med_price", "R", 3, "decimal"},
		},
	},

	{"Steel",
		"Hot Rolled Coil Black Sea",
		"steelmint.com",
		"Not specified",
		"usd/t",
		"A",
		[]Property{{"min_price", "AB", 203, "decimal"},
			{"max_price", "AC", 203, "decimal"},
			{"med_price", "AD", 3, "decimal"},
		},
	},

	{"Steel",
		"Armature A1",
		"Not specified",
		"Not specified",
		"rub/t",
		"A",
		[]Property{
			{"med_price", "AH", 212, "decimal"},
		},
	},

	{"Steel",
		"Hot Rolled Sheet",
		"Not specified",
		"Not specified",
		"rub/t",
		"A",
		[]Property{
			{"med_price", "AL", 212, "decimal"},
		},
	},

	{"Steel",
		"Cold Rolled Sheet",
		"Not specified",
		"Not specified",
		"rub/t",
		"A",
		[]Property{
			{"med_price", "AP", 212, "decimal"},
		},
	},

	{"Ferroalloy",
		"FeMn76",
		"Not specified",
		"Not specified",
		"usd/t",
		"A",
		[]Property{
			{"med_price", "F", 3, "decimal"},
			{"min_price", "D", 11, "decimal"},
			{"max_price", "E", 11, "decimal"},
		},
	},

	{"Ferroalloy",
		"FeSi75",
		"Not specified",
		"Not specified",
		"usd/t",
		"A",
		[]Property{
			{"med_price", "M", 3, "decimal"},
			{"min_price", "K", 11, "decimal"},
			{"max_price", "L", 11, "decimal"},
		},
	},

	{"Ferroalloy",
		"SiMn65",
		"Not specified",
		"Not specified",
		"usd/t",
		"A",
		[]Property{
			{"med_price", "T", 3, "decimal"},
			{"min_price", "R", 11, "decimal"},
			{"max_price", "S", 11, "decimal"},
		},
	},

	{"Ferroalloy",
		"HC FeCr",
		"Not specified",
		"Not specified",
		"usd/lb",
		"A",
		[]Property{
			{"med_price", "AA", 3, "decimal"},
			{"min_price", "Y", 11, "decimal"},
			{"max_price", "Z", 11, "decimal"},
		},
	},

	{"Ferroalloy",
		"LC FeCr",
		"Not specified",
		"Not specified",
		"usd/lb",
		"A",
		[]Property{
			{"med_price", "AH", 3, "decimal"},
			{"min_price", "AF", 11, "decimal"},
			{"max_price", "AG", 11, "decimal"},
		},
	},

	{"Ferroalloy",
		"Mn Ore (36-38)",
		"Not specified",
		"Not specified",
		"usd/dmt",
		"A",
		[]Property{
			{"med_price", "AO", 3, "decimal"},
			{"min_price", "AM", 11, "decimal"},
			{"max_price", "AN", 11, "decimal"},
		},
	},

	{"Ferroalloy",
		"Cr Ore",
		"Not specified",
		"Not specified",
		"usd/t",
		"A",
		[]Property{
			{"med_price", "AV", 3, "decimal"},
			{"min_price", "AT", 11, "decimal"},
			{"max_price", "AU", 11, "decimal"},
		},
	},

	{"Graphite Electrodes",
		"Graphite Electrodes 450mm Shanxi",
		"Not specified",
		"Not specified",
		"usd/t",
		"A",
		[]Property{
			{"med_price", "D", 212, "decimal"},
		},
	},

	{"Graphite Electrodes",
		"Graphite Electrodes 600mm Shanxi",
		"Not specified",
		"Not specified",
		"usd/t",
		"A",
		[]Property{
			{"med_price", "H", 212, "decimal"},
		},
	},

	{"Stock",
		"Manganese Ore Stock",
		"ferroalloynet.com",
		"Not specified",
		"million tons",
		"B",
		[]Property{
			{"med_price", "D", 3, "decimal"},
		},
	},

	{"Stock",
		"Chrome Ore Stock",
		"ferroalloynet.com",
		"Not specified",
		"million tons",
		"B",
		[]Property{
			{"med_price", "H", 3, "decimal"},
		},
	},

	{"Stock",
		"Iron Ore Stock",
		"steelmint.com ",
		"China",
		"million tons",
		"B",
		[]Property{
			{"med_price", "H", 3, "decimal"},
		},
	},
}
