package model

var InitDaily = []DailyMaterial{
	{"Daily",
		"ПВЖ, 80% Feмет",
		"Сырьевые материалы",
		"steelmint.com",
		"Индия",
		"DAP",
		"$/т",
		"A",
		[]Property{
			{"Средняя цена", "BM", 4, "decimal"},
		},
		false,
		ConvSettings{},
	},
	{"Daily",
		"Рулон, г/к",
		"Сталь",
		"steelmint.com",
		"Индия",
		"FOB",
		"$/т",
		"A",
		[]Property{
			{"Средняя цена", "DQ", 6, "decimal"},
			{"Мин цена", "DO", 6, "decimal"},
			{"Макс цена", "DP", 6, "decimal"},
		},
		false,
		ConvSettings{},
	},
	{"Daily",
		"Рулон, х/к",
		"Cталь",
		"steelmint.com",
		"Индия",
		"FOB",
		"$/т",
		"A",
		[]Property{
			{"Мин цена", "ER", 4, "decimal"},
			{"Макс цена", "ES", 4, "decimal"},
			{"Средняя цена", "ET", 4, "decimal"},
		},
		false,
		ConvSettings{},
	},
	{"Daily",
		"FeSi; 75% Si",
		"Cталь",
		"ferroalloynet.com",
		"Внутренняя Монголия",
		"EXW",
		"¥/т",
		"A",
		[]Property{
			{"Мин цена", "GD", 4, "decimal"},
			{"Макс цена", "GE", 4, "decimal"},
			{"Средняя цена", "GF", 4, "decimal"},
		},
		false,
		ConvSettings{},
	},
	{"Daily",
		"FeSi; 75% Si",
		"Ферросплавы и руды",
		"ferroalloynet.com",
		"Китай",
		"FOB",
		"$/т",
		"A",
		[]Property{
			{"Средняя цена", "GO", 4, "decimal"},
		},
		false,
		ConvSettings{},
	},
	{"Daily",
		"FeSi; 75% Si",
		"Ферросплавы и руды",
		"CRU (18 строчка)",
		"США",
		"EXW",
		"$/т",
		"A",
		[]Property{
			{"Средняя цена", "HG", 4, "decimal"},
		},
		true,
		ConvSettings{
			true,
			UsdcPoundToUsdTonn,
			75,
		},
	},
	{"Daily",
		"SiMn; 65% Si, 17% Mn",
		"Ферросплавы и руды",
		"ferroalloynet.com",
		"Гуанси",
		"EXW",
		"¥/т",
		"A",
		[]Property{
			{"Средняя цена", "HQ", 4, "decimal"},
		},
		true,
		ConvSettings{},
	},
	{"Daily",
		"SiMn; 65% Si, 16% Mn",
		"Ферросплавы и руды",
		"ferroalloynet.com",
		"Индия",
		"FOB",
		"$/т",
		"A",
		[]Property{
			{"Средняя цена", "HZ", 4, "decimal"},
		},
		true,
		ConvSettings{},
	},
	{"Daily",
		"SiMn; 65% Mn",
		"Ферросплавы и руды",
		"CRU (33 строчка)",
		"США",
		"EXW",
		"$/т",
		"A",
		[]Property{
			{"Средняя цена", "II", 4, "decimal"},
		},
		true,
		ConvSettings{
			true,
			UsdcPoundToUsdTonn,
			100,
		},
	},
	{"Daily",
		"HC FeCr; 55% Cr, 10% C",
		"Ферросплавы и руды",
		"CRU (33 строчка)",
		"ferroalloynet.com",
		"EXW",
		"$/т",
		"A",
		[]Property{
			{"Средняя цена", "JT", 4, "decimal"},
		},
		true,
		ConvSettings{},
	},
	{"Daily",
		"HC FeCr; 70% Cr, 0,5% Si",
		"Ферросплавы и руды",
		"ferroalloynet.com",
		"Казахстан",
		"CIF",
		"USDc/фунт",
		"A",
		[]Property{
			{"Средняя цена", "KC", 4, "decimal"},
		},
		false,
		ConvSettings{},
	},
	{"Daily",
		"HC FeCr; 60% Cr, 4% Si",
		"Ферросплавы и руды",
		"ferroalloynet.com",
		"Индия",
		"CIF",
		"USDc/фунт",
		"A",
		[]Property{
			{"Средняя цена", "KL", 4, "decimal"},
		},
		false,
		ConvSettings{},
	},
	{"Daily",
		"HC FeCr; 48-50% Cr, 5% Si",
		"Ферросплавы и руды",
		"ferroalloynet.com",
		"ЮАР",
		"CIF",
		"USDc/фунт",
		"A",
		[]Property{
			{"Средняя цена", "KU", 4, "decimal"},
		},
		false,
		ConvSettings{},
	},
	{"Daily",
		"LC FeCr; 52-60% Cr, 0,25% C",
		"Ферросплавы и руды",
		"ferroalloynet.com",
		"Внутренняя Монголия",
		"EXW",
		"¥/т",
		"A",
		[]Property{
			{"Средняя цена", "LM", 4, "decimal"},
		},
		true,
		ConvSettings{},
	},
	{"Daily",
		"LC FeCr; 0,1% C",
		"Ферросплавы и руды",
		"CRU (19 строчка)",
		"США",
		"EXW",
		"USDc/фунт",
		"A",
		[]Property{
			{"Средняя цена", "ME", 4, "decimal"},
		},
		true,
		ConvSettings{},
	},
	{"Daily",
		"Чугун",
		"Сырьевые материалы",
		"steelmint.com",
		"Индия",
		"FOB",
		"$/т",
		"A",
		[]Property{
			{"Средняя цена", "CE", 4, "decimal"},
		},
		false,
		ConvSettings{},
	},
	{"Daily",
		"Заготовка",
		"Сталь",
		"steelmint.com",
		"Индия",
		"FOB",
		"$/т",
		"A",
		[]Property{
			{"Средняя цена", "CW", 4, "decimal"},
		},
		false,
		ConvSettings{},
	},
	{"Daily",
		"Арматура",
		"Сталь",
		"steelmint.com",
		"Россия",
		"FOB",
		"$/т",
		"A",
		[]Property{
			{"Средняя цена", "FL", 4, "decimal"},
		},
		false,
		ConvSettings{},
	},
}

func UsdcPoundToUsdTonn(num float64, rate float64) float64 {
	return (num / 100) / 0.00045 * (rate / 100)
}
